name: flutter_feature_manager
description: "A new Flutter package project."
version: 0.1.4
# homepage:

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  firebase_remote_config: ^5.2.0
  flutter:
    sdk: flutter
  logging: ^1.2.0
  mocktail: ^1.0.3
  package_info_plus: ^8.0.0
  posthog_flutter: ^4.9.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter


